name: Validate JSON

on:
  pull_request:
    paths:
      - 'speakers.json'
      - 'topics.json'
      - 'schemas/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v5
        with:
          schema_mappings: |
            - type: json
              schema: ./schemas/topics.json
              files:
                - ./topics.json
              json_schema_version: draft-07
            - type: json
              schema: ./schemas/speakers.json
              files:
                - ./speakers.json
              json_schema_version: draft-07
